logging:
  level:
    root: WARN
    com:
      grayash: DEBUG
      github:
        grayash: DEBUG
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      hibernate: WARN
      apache:
        commons:
          dbcp2: ERROR
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
CrudService:
  ribbon:
    listOfServers: http://localhost:8901
feign:
  hystrix:
    enabled: false